version: '3.9'

services:
  backend:
    build:
      context: ./ProjectSoftwareBackend
    container_name: flask_backend
    ports:
      - "5000:5000"
    volumes:
      - ./ProjectSoftwareBackend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./ProjectSoftwareFrontend/dietaFrontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
