"""Agregar tabla Publicacion

Revision ID: 188059eb77bf
Revises: 0a17f4677e0a
Create Date: 2025-06-29 17:07:51.059126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188059eb77bf'
down_revision = '0a17f4677e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Intercambio', 'Donación', name='tipo_publicacion_enum'), nullable=False),
    sa.Column('estado_libro', sa.Enum('Nuevo', 'Como nuevo', 'Bueno', 'Aceptable', 'Dañado', name='estado_libro_enum'), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('comentarios_adicionales', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    # ### end Alembic commands ###
