"""empty message

Revision ID: 3185c1e0e4b9
Revises: d83d75db4efd
Create Date: 2025-07-11 15:53:30.805026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3185c1e0e4b9'
down_revision = 'd83d75db4efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('estado_libro',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('NUEVO', 'USADO', 'BUEN_ESTADO', 'COMO_NUEVO', name='estadolibroenum'),
               existing_nullable=False)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aceptado_por_usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_solicitud_usuario', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aceptado_por_usuario_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('mensaje')

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('estado_libro',
               existing_type=sa.Enum('NUEVO', 'USADO', 'BUEN_ESTADO', 'COMO_NUEVO', name='estadolibroenum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
