"""Agregar campo imagen al modelo Libro

Revision ID: 5107e2136cea
Revises: 912c128b9aed
Create Date: 2025-07-06 02:59:59.562104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5107e2136cea'
down_revision = '912c128b9aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('genero_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('genero_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
