"""Agregar tabla Intercambio

Revision ID: 9e73c33e0643
Revises: 3185c1e0e4b9
Create Date: 2025-07-11 17:16:52.602796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e73c33e0643'
down_revision = '3185c1e0e4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intercambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('book_offered_id', sa.Integer(), nullable=False),
    sa.Column('book_requested_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_offered_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['book_requested_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_solicitud_usuario_solicitante", 'usuario', ['aceptado_por_usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint("fk_solicitud_usuario_solicitante", type_='foreignkey')

    # op.drop_table('intercambio')
    # ### end Alembic commands ###
