"""Añadir campo imagen a Libro

Revision ID: d83d75db4efd
Revises: 5107e2136cea
Create Date: 2025-07-06 03:24:44.218193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83d75db4efd'
down_revision = '5107e2136cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
