"""Fix FK a usuario y libro

Revision ID: fd5aa27f710f
Revises: 188059eb77bf
Create Date: 2025-06-29 19:09:00.355599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5aa27f710f'
down_revision = '188059eb77bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('estado_libro',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NUEVO', 'USADO', name='estadolibroenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('estado_libro',
               existing_type=sa.Enum('NUEVO', 'USADO', name='estadolibroenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
